# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the SAP systems, the workload zone (landscape)  |
# |      using Terraform.                                                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              cleanup_sap
    displayName:                       Remove the SAP system
    type:                              boolean
    default:                           true

  - name:                              sap_system
    displayName:                       "SAP System configuration name, use this format: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           DEV-WEEU-SAP01-X00

  - name:                              cleanup_zone
    displayName:                       Remove the SAP workload zone
    type:                              boolean
    default:                           true

  - name:                              workload_zone_name
    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           TEST-SECE-SAP02

  - name:                              use_deployer
    displayName:                       Run removal on self hosted agent
    type:                              boolean
    default:                           true

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

stages:
  - stage:                             Remove_SAP_systems
    displayName:                       "Removing the SAP System"
    condition:                         and(not(failed()), not(canceled()), eq(${{ parameters.cleanup_sap }}, true))
    variables:
      - template:                      variables/10-remover-terraform-variables.yaml
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          sap_system:                  ${{ parameters.sap_system }}
    jobs:
      - job:                           Remove_SAP_systems
        displayName:                   "Removing the SAP System"
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      TerraformInstaller@1
            displayName:               Install terraform
            inputs:
              terraformVersion:        latest
          - task:                      AzureCLI@2
            displayName:               "Remove the SAP system"
            inputs:
              azureSubscription:       "${{ parameters.workload_zone_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/10-remover-terraform-system.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          true
            env:
              APPLICATION_CONFIGURATION_NAME:        $(APPLICATION_CONFIGURATION_NAME)
              ARM_SUBSCRIPTION_ID:                   $(ARM_SUBSCRIPTION_ID)
              ARM_USE_MSI:                           true
              AZURE_DEVOPS_EXT_PAT:                  $(System.AccessToken)
              CONFIG_REPO_PATH:                      ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:                    $(CONTROL_PLANE_NAME)
              SAP_AUTOMATION_REPO_PATH:              ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:                    $(System.AccessToken)
              TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME: $(TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME)
              TF_IN_AUTOMATION:                      true
              TF_LOG:                                $(TF_LOG)
              TF_VAR_use_spn:                        $(Use_MSI)
              USE_MSI:                               $(Use_MSI)
              WORKLOAD_ZONE_NAME:                    ${{ parameters.workload_zone_name }}
  - stage:                             Remove_SAP_workload_zone
    displayName:                       "Removing the SAP workload zone"
    condition:                         and(not(failed()), not(canceled()), eq(${{ parameters.cleanup_zone }}, true))
    variables:
      - template:                      variables/10-remover-terraform-variables.yaml
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          sap_system:                  ${{ parameters.sap_system }}

    jobs:
      - job:                           Remove_SAP_workload_zone
        displayName:                   Remove the SAP Workload Zone
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      TerraformInstaller@1
            displayName:               Install terraform
            inputs:
              terraformVersion:        latest
          - task:                      AzureCLI@2
            displayName:               "Remove the SAP workload zone"
            inputs:
              azureSubscription:       "${{ parameters.workload_zone_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/10-remover-terraform-workload-zone.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          true
            env:
              APPLICATION_CONFIGURATION_NAME:        $(APPLICATION_CONFIGURATION_NAME)
              ARM_SUBSCRIPTION_ID:                   $(ARM_SUBSCRIPTION_ID)
              ARM_USE_MSI:                           true
              AZURE_DEVOPS_EXT_PAT:                  $(System.AccessToken)
              CONFIG_REPO_PATH:                      ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:                    $(CONTROL_PLANE_NAME)
              SAP_AUTOMATION_REPO_PATH:              ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:                    $(System.AccessToken)
              TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME: $(TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME)
              TF_IN_AUTOMATION:                      true
              TF_LOG:                                $(TF_LOG)
              TF_VAR_use_spn:                        $(Use_MSI)
              USE_MSI:                               $(Use_MSI)
              WORKLOAD_ZONE_NAME:                    ${{ parameters.workload_zone_name }}
