# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the SAP systems, the workload zone (landscape)  |
# |      and the region via ARM resource group deletion.                       |
# |                                                                            |
# |      The pipeline can be used as fallback in case the terraform            |
# |      destroy doesn't remove everything.                                    |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              cleanup_sap
    displayName:                       Remove the SAP system
    type:                              boolean
    default:                           true

  - name:                              sap_system
    displayName:                       "SAP System SID"
    type:                              string
    default:                           X00

  - name:                              cleanup_workload_zone
    displayName:                       Remove the SAP workload zone
    type:                              boolean
    default:                           true

  - name:                              workload_zone_name
    displayName:                       "SAP workload zone configuration name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           DEV-WEEU-SAP01

  - name:                              cleanup_control_plane
    displayName:                       Remove the control plane
    type:                              boolean
    default:                           true

  - name:                              control_plane_name
    displayName:                       Environment (MGMT, ...)
    type:                              string
    default:                           MGMT

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

stages:
  - stage:                             Remove_SAP_systems
    displayName:                       Remove SAP System
    condition:                         eq(${{ parameters.cleanup_sap }}, true)
    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
    jobs:
      - job:                           Remove_SAP_system_RG
        displayName:                   Remove SAP System ${{ parameters.sap_system }}
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        steps:
          - task:                      AzureResourceManagerTemplateDeployment@3
            displayName:               Remove Resource Group $(sap_system_foldername)
            inputs:
              deploymentScope:                "Resource Group"
              azureResourceManagerConnection: "${{ parameters.workload_zone_name }}_Service_Connection"
              subscriptionId:                 "$(ARM_SUBSCRIPTION_ID)"
              action:                         "DeleteRG"
              resourceGroupName:              ${{ parameters.sap_system }}

      - job:                           Remove_sap_deployment_artifacts_in_WORKSPACES
        dependsOn:                     Remove_SAP_system_RG
        displayName:                   Remove SAP System deployment artifacts from WORKSPACES
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       "${{ parameters.workload_zone_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/11-remover-arm-fallback-system.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          false
            displayName:               Remove_SAP_infrastructure
            env:
              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              SAP_SYSTEM_FOLDERNAME:    ${{ parameters.sap_system }}

  - stage:                             Remove_SAP_workload_zone
    displayName:                       Remove SAP workload zone
    condition:                         eq(${{ parameters.cleanup_workload_zone }}, true)
    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          SAP_AUTOMATION_REPO_PATH:    ${{ parameters.sap_automation_repo_path }}
          CONFIG_REPO_PATH:            ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
    jobs:
      - job:                           Remove_SAP_workload_zone
        displayName:                   Remove SAP workload zone ${{ parameters.workload_zone_name }}
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        steps:
          - task:                      AzureResourceManagerTemplateDeployment@3
            displayName:               Remove Resource Group
            inputs:
              deploymentScope:                "Resource Group"
              azureResourceManagerConnection: "${{ parameters.workload_zone_name }}_Service_Connection"
              subscriptionId:                 "$(ARM_SUBSCRIPTION_ID)"
              action:                         "DeleteRG"
              resourceGroupName:              "$(workload_zone_foldername)"

      - job:                           Remove_zone_deployment_artifacts_in_WORKSPACES
        dependsOn:                     Remove_SAP_workload_zone
        displayName:                   Remove Workload Zone deployment artifacts
        variables:
          - group:                     SDAF-${{ parameters.workload_zone_name }}
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       "${{ parameters.workload_zone_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/11-remover-arm-fallback-workload-zone.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          false
            displayName:               Remove SAP Workload Zone deployment artifacts from WORKSPACES
            env:
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              SYSTEM_ACCESSTOKEN:       $(System.AccessToken)
              WORKLOAD_ZONE_FOLDERNAME: ${{ parameters.workload_zone_name }}

  - stage:                             Remove_Control_plane
    displayName:                       Remove Control Plane
    condition:                         eq(${{ parameters.cleanup_control_plane }}, true)

    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
    jobs:
      - job:                           Remove_control_plane_deployment
        displayName:                   Remove Control Plane deployment
        variables:
          - group:                     SDAF-${{ parameters.control_plane_name }}
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       "${{ parameters.control_plane_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/11-remover-arm-fallback-control-plane.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          false

            displayName:               Remove Control Plane deployment artifacts from WORKSPACES
            env:
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              USE_MSI:                  $(Use_MSI)
              PAT:                      $(System.AccessToken)
