# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows builds the SAP Container Image with GitHub Actions      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: Build image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "37 4 1 * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout main respository
      uses: actions/checkout@v4

    - name: Checkout SAP-automation-samples
      uses: actions/checkout@v4
      with:
        repository: Azure/SAP-automation-samples
        path: SAP-automation-samples

    - name: Determine package versions
      id: versions
      run: |
        jq_version=$(gh api https://api.github.com/repos/mikefarah/yq/releases/latest| jq '.name' -r)
        echo "jq=$jq_version" >> $GITHUB_OUTPUT

        tf_version=$(curl -s https://releases.hashicorp.com/terraform/index.json | jq -r '.versions | keys[]' | grep -Ev 'alpha|beta|rc' | sort -V | tail -n 1)
        echo "tf=$tf_version" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: |
          JQ_VERSION=${{ steps.versions.outputs.jq }}
          TF_VERSION=${{ steps.versions.outputs.tf }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
